package com.woodpeckerbros.watchreminder;

import android.content.Context;

import java.util.HashMap;
import java.util.Map;

public class UiText {
    private static final Map<String, String> EN = new HashMap<>();
    private static final Map<String, Integer> RES = new HashMap<>();

    static {
        res("תזכורת חדשה", R.string.ui_new_reminder);
        res("עריכת תזכורת", R.string.ui_edit_reminder);
        res("שם, זמן, סוג ופעילות", R.string.ui_reminder_editor_subtitle);
        res("שם", R.string.ui_name);
        res("תיאור (אופציונלי)", R.string.ui_description_optional);
        res("תזכורת", R.string.ui_default_reminder_name);
        res("צריך לבחור זמן עתידי", R.string.ui_choose_future_time);
        res("מיקום", R.string.ui_location);
        res("פעילה", R.string.ui_enabled_feminine);
        res("חיונית", R.string.ui_critical);
        res("קבועה", R.string.ui_fixed);
        res("חד פעמית", R.string.ui_one_time);
        res("מחזורית", R.string.ui_repeating);
        res("מחזוריות", R.string.ui_repeating_title);
        res("אירוע שנתי", R.string.ui_annual_event);
        res("שנתית", R.string.ui_annual);
        res("שעה", R.string.ui_hour);
        res("דקה", R.string.ui_minute);
        res("דקות", R.string.ui_minutes);
        res("זמני הלכה", R.string.ui_halacha_times);
        res("לפני / אחרי", R.string.ui_before_after);
        res("שמירה", R.string.ui_save);
        res("ביטול", R.string.ui_cancel);
        res("כל", R.string.ui_every);
        res("שעות", R.string.ui_hours);
        res("ימים", R.string.ui_days);
        res("שבועות", R.string.ui_weeks);
        res("חודשים", R.string.ui_months);
        res("שנים", R.string.ui_years);
        res("תאריך עברי", R.string.ui_hebrew_date);
        res("התאריך הוא נקודת ההתחלה. בשנים/חודשים לפי תאריך עברי, האפליקציה ממירה בכל פעם לתאריך לועזי מתאים.", R.string.ui_periodic_hebrew_hint);
        res("שעות לפני", R.string.ui_hours_before);
        res("מספר הבא", R.string.ui_next_number);
        res("מספר התחלתי", R.string.ui_serial_number_hint);
        res("אם הוזן מספר התחלתי, הוא יוצג בסוגריים ויעלה ב-1 בכל שנה.", R.string.ui_annual_counter_hint);
        res("תאריך", R.string.ui_date);
        res("יום", R.string.ui_day);
        res("חודש", R.string.ui_month);
        res("שנה", R.string.ui_year);
        res("לא זמין", R.string.ui_unavailable);
        res("היום", R.string.ui_today);
        res("מחר", R.string.ui_tomorrow);
        res("אתמול", R.string.ui_yesterday);
        res("אין התראות שחלפו", R.string.ui_no_past_alerts);
        res("ביטול בוצע", R.string.ui_done_undo);
        res("החלה", R.string.ui_apply);
        res("שחזור", R.string.ui_restore);
        res("עריכה", R.string.ui_edit);
        res("מחיקה", R.string.ui_delete);
        res("יום לפני", R.string.ui_previous_day);
        res("יום אחרי", R.string.ui_next_day);

        put("הוספה", "Add");
        put("+ תזכורת", "+ Reminder");
        put("היסטוריה", "History");
        put("תזכורות", "Reminders");
        put("כל התזכורות", "All Reminders");
        put("לחיצה לעריכה · לחיצה ארוכה לפעולות", "Tap to edit · long press for actions");
        put("חזרה לבית", "Back Home");
        put("מה חשוב עכשיו", "What matters now");
        put("התזכורת הבאה", "Next Reminder");
        put("אחר כך", "Coming Up");
        put("גישה מהירה", "Quick Access");
        put("אין תזכורות קרובות", "No Upcoming Reminders");
        put("אפשר להוסיף תזכורת חדשה בלחיצה אחת", "Add a new reminder in one tap");
        put("בוקר טוב", "Good morning");
        put("צהריים טובים", "Good afternoon");
        put("ערב טוב", "Good evening");
        put("לחיצה ארוכה על תזכורת פותחת פעולות אפשריות", "Long press a reminder to open actions");
        put("אין תזכורות", "No reminders");
        put("טוען תזכורות...", "Loading reminders...");
        put("טוען עוד תזכורות...", "Loading more reminders...");
        put("צריך לאשר Alarms & reminders כדי לקבל תזכורות בזמן", "Allow Alarms & reminders to receive reminders on time");
        put("לחץ כאן כדי לאשר Alarms & reminders לתזכורות מדויקות", "Tap here to allow Alarms & reminders for exact reminders");
        put("צריך לאשר התראות במסך מלא כדי שהתזכורת תיפתח על המסך", "Allow full-screen notifications so reminders can open on screen");
        put("דחה", "Snooze");
        put("זמני היום בהלכה", "Halachic Times");
        put("זמני היום", "Halachic Times");
        put("תזכורת לברכה", "Blessing Reminder");
        put("תזכורת", "Reminder");
        put("הגדרות", "Settings");
        put("חזרה", "Back");
        put("שמירה", "Save");
        put("ביטול", "Cancel");
        put("ניקוי הכל", "Clear All");
        put("מנקה היסטוריה...", "Clearing history...");
        put("ההיסטוריה נמחקה", "History cleared");
        put("לא הצלחתי לנקות את ההיסטוריה", "Could not clear history");
        put("ניקוי לוגים", "Clear Logs");
        put("לוגים", "Logs");
        put("לוגים לטלפון", "Send Logs");
        put("לבדיקת תזכורות שלא קופצות בזמן", "For diagnosing reminders that do not alert on time");
        put("גיבוי ושחזור", "Backup and Restore");
        put("גיבוי לטלפון", "Back Up to Phone");
        put("שחזור מהטלפון", "Restore from Phone");
        put("התראה", "Alert");
        put("תזכורות רגילות", "Regular Reminders");
        put("בדיקת רקע לתזכורות", "Background Reminder Check");
        put("המתנה לענידת השעון", "Waiting for Watch to Be Worn");
        put("רטט", "Vibration");
        put("צלצול", "Sound");
        put("בחירת צלצול", "Choose Sound");
        put("צלצול ברירת מחדל", "Default sound");
        put("עוצמת צלצול", "Sound volume");
        put("אורך התראה בשניות", "Alert length, seconds");
        put("לא הצלחתי לפתוח בחירת צלצול", "Could not open sound picker");
        put("רגיל", "Normal");
        put("עדין", "Gentle");
        put("חזק", "Strong");
        put("ארוך", "Long");
        put("ללא רטט", "No vibration");
        put("אורך רטט בשניות", "Vibration length, seconds");
        put("בדיקת רקע פעילה", "Background check active");
        put("ברירת מחדל: כל 3 דקות", "Default: every 3 minutes");
        put("דקות", "Minutes");
        put("שניות", "Seconds");
        put("דחייה אוטומטית", "Auto Snooze");
        put("אם אין תגובה, המסך נסגר והתזכורת נדחית", "If there is no response, the screen closes and the reminder is snoozed");
        put("המתנה לתגובה לפני סגירה (שניות)", "Wait for response before closing (seconds)");
        put("הקפצה חוזרת לאחר סגירה (דקות)", "Repeat after closing (minutes)");
        put("כמה דקות אחרי החיוב להזכיר לברך", "Minutes after becoming obligated to send the blessing reminder");
        put("זמני שקט - לא להפריע", "Quiet Times - Do Not Disturb");
        put("ברכת הלבנה", "Birkat Halevana");
        put("סמן שבירכתי", "Mark as Recited");
        put("דף היומי", "Daf Yomi");
        put("ספירת העומר", "Omer Count");
        put("צום לסירוגין", "Intermittent Fasting");
        put("מצב נוכחי", "Current Status");
        put("שעות צום וחלון אכילה", "Fasting and Eating Hours");
        put("חלון האכילה מחושב אוטומטית מתוך 24 שעות", "The eating window is calculated automatically from 24 hours");
        put("שעות צום", "Fasting Hours");
        put("התחלת אכילה ראשונית", "Initial Eating Start");
        put("לדוגמה 12:00 עם 19 שעות צום יוצר חלון 12:00-17:00", "For example, 12:00 with 19 fasting hours creates a 12:00-17:00 window");
        put("סיימתי לאכול", "I Finished Eating");
        put("התחלתי לאכול", "I Started Eating");
        put("חלון האכילה התחיל עכשיו", "The eating window started now");
        put("סומן שהתחלת לאכול ב-", "Marked that you started eating at ");
        put("אפשר לבחור זמן סיום רק אחרי פתיחת חלון האכילה", "The finish time must be after the eating window opens");
        put("סומן שסיימת לאכול. חלון האכילה הבא יתעדכן לפי זמן הסיום.", "Marked as finished eating. The next eating window will use the finish time.");
        put("בחירת זמן ידנית", "Choose Time Manually");
        put("זמן סיום", "Finish Time");
        put("זמן התחלה", "Start Time");
        put("התחלתי לאכול בשעה", "I Started Eating at");
        put("סיימתי לאכול בשעה", "I Finished Eating at");
        put("בחר זמן התחלה", "Choose Start Time");
        put("בחר זמן סיום", "Choose Finish Time");
        put("אי אפשר לבחור זמן סיום עתידי", "The finish time cannot be in the future");
        put("סומן שסיימת לאכול ב-", "Marked that you finished eating at ");
        put("אפשר להתחיל לאכול", "You Can Start Eating");
        put("עוד חצי שעה לסיום", "30 Minutes Remaining");
        put("חלון האכילה ייסגר בעוד חצי שעה.", "The eating window will close in 30 minutes.");
        put("חלון האכילה נסגר", "Eating Window Closed");
        put("נגמר חלון זמן האכילה להיום.", "Today's eating window has ended.");
        put("יש לך תזכורת לצום לסירוגין.", "You have an intermittent fasting reminder.");
        put("תחזור עד שתלחץ הבנתי.", "This reminder will return until you tap Got it.");
        put("הצום נגמר ב:", "Fast ends at:");
        put("הצום מתחיל ב:", "Fast starts at:");
        put("מיקום זמני הלכה", "Halachic Times Location");
        put("מיקום חדש", "Refresh Location");
        put("זהה שם עיר", "Identify City");
        put("מזהה שם עיר...", "Identifying city...");
        put("שם העיר עודכן", "City name updated");
        put("אין תשובה מהשרת; הוצג יישוב קרוב", "No server response; showing a nearby locality");
        put("אין תשובה מהשרת; נשמרו הקואורדינטות", "No server response; coordinates were saved");
        put("המיקום עודכן", "Location updated");
        put("לשליחה כשיש תקלה בתזכורות", "Send when there is a reminder issue");
        put("גיבוי ושחזור מתבצעים דרך אפליקציית הטלפון", "Backup and restore are handled through the phone app");
        put("פעיל", "Active");
        put("פעילה", "Active");
        put("כבוי", "Off");
        put("תזכורת דף היומי פעילה", "Daf Yomi reminder active");
        put("זמן לתזכורת", "Time for a Reminder");
        put("אפשר לדחות", "Snooze options");
        put("בדיקת לימוד דף היומי", "Daf Yomi Study Check");
        put("תיקון סימון", "Fix Marking");
        put("אם סימנת בטעות שלמדת, אפשר להחזיר דף לרשימת ההשלמות", "If you marked a page learned by mistake, you can move it back to the catch-up list");
        put("אין דפים שסומנו כלמדתי בימים האחרונים", "No pages were marked learned in the last few days");
        put("סמן כלא למדתי", "Mark Not Learned");
        put("דפים להשלמה", "Pages to Catch Up");
        put("אין דפים שמסומנים כלא למדתי", "No pages are marked as not learned");
        put("סמן הכל כהושלם", "Mark All as Completed");
        put("סימון כל הדפים כהושלמו", "Mark All Pages as Completed");
        put("האם לסמן את כל הדפים שברשימת ההשלמה כנלמדו? פעולה זו תסיר את כולם מהרשימה.", "Mark every page in the catch-up list as learned? This will remove all of them from the list.");
        put("המשך", "Continue");
        put("למדתי את הדף", "I Learned This Page");
        put("תזכורת ספירת העומר פעילה", "Omer reminder active");
        put("תזכורת לספירת העומר", "Omer Count Reminder");
        put("כמה דקות אחרי צאת הכוכבים להזכיר", "Minutes after nightfall to send the reminder");
        put("דקות אחרי צאת הכוכבים", "Minutes after nightfall");
        put("מחוץ לימי הספירה כרגע", "Outside the Omer period right now");
        put("התזכורת הקרובה:", "Next reminder:");
        put("בחירת תאריך", "Choose Date");
        put("הצג", "Show");
        put("בחירה לפי תאריך לועזי", "Choose by Gregorian Date");
        put("בחירה לפי תאריך עברי", "Choose by Hebrew Date");
        put("שפה", "Language");
        put("שפת הממשק", "Interface language");
        put("אוטומטי לפי השעון", "Automatic by watch language");
        put("עברית", "Hebrew");
        put("אנגלית", "English");
        put("שעון מעורר חכם", "Smart Alarm");
        put("זמנים יהודיים", "Jewish Times");
        put("קריאת שמע של ערבית בזמנה", "Evening Shema on Time");
        put("כמה דקות אחרי צאת הכוכבים לתזכר. אם הזמן כבר עבר, התזכורת תוגדר לפי ההגדרה הכללית למעלה.", "Remind this many minutes after nightfall. If that time has passed, the general setting above will be used.");
        put("רטט וצלילים", "Vibration and Sounds");
        put("הגדרות מתקדמות", "Advanced Settings");
        put("מצב יהודי כבוי", "Jewish Mode is off");
        put("מצב יהודי", "Jewish Mode");
        put("מציג תאריך עברי, זמני הלכה, ברכות, דף יומי וספירת העומר", "Shows Hebrew dates, halachic times, blessings, Daf Yomi, and the Omer count");
        put("אם ההתראות לא מתקבלות בזמן, אפשר להפעיל בדיקת רקע ולבחור כל כמה דקות לדגום. הגדרה זו עלולה לצרוך יותר סוללה.", "If reminders are not arriving on time, enable background checks and choose how often to sample. This setting may use more battery.");
        put("לתזכר ימים יהודיים", "Jewish day reminders");
        put("ימים יהודיים", "Jewish days");
        put("תזכורת תקופה", "Tekufa Reminder");
        put("לתזכר זמן תקופה", "Tekufa time reminder");
        put("זמן התקופה", "Tekufa time");
        put("תקופת ניסן", "Tekufat Nisan");
        put("תקופת תמוז", "Tekufat Tammuz");
        put("תקופת תשרי", "Tekufat Tishrei");
        put("תקופת טבת", "Tekufat Tevet");
        put("תזכורת מקדימה לזמן התקופה", "Advance tekufa reminder");
        put("זמן התקופה מתחיל עכשיו", "The tekufa window starts now");
        put("חלון", "Window");
        put("יש להימנע משתיית מים גלויים מ־", "Avoid drinking uncovered water from ");
        put("עד", "to");
        put("לא נמצאה תקופה קרובה", "No upcoming tekufa found");
        put("יום כיפור קטן", "Yom Kippur Katan");
        put("פרשת השבוע", "Weekly Parsha");
        put("שבת מיוחדת", "Special Shabbat");
        put("זמני שבת", "Shabbat Times");
        put("הדלקת נרות", "Candle Lighting");
        put("צאת שבת", "Shabbat Ends");
        put("צאת שבת ר״ת", "Rabbeinu Tam");
        put("עלות השחר", "Dawn");
        put("זריחה", "Sunrise");
        put("סוף זמן שמע מג״א", "Latest Shema (MGA)");
        put("סוף זמן שמע גר״א", "Latest Shema (GRA)");
        put("סוף זמן ברכות ק״ש", "Latest Shema Blessings");
        put("חצות", "Halachic Midday");
        put("חצות יום", "Halachic Midday");
        put("חצות לילה", "Halachic Midnight");
        put("צ.כוכבים ר״ת", "Rabbeinu Tam");
        put("דף היומי בבלי", "Daf Yomi Bavli");
        put("דף היומי ירושלמי", "Daf Yomi Yerushalmi");
        put("מנחה גדולה", "Mincha Gedola");
        put("מנחה קטנה", "Mincha Ketana");
        put("פלג המנחה", "Plag HaMincha");
        put("שקיעה", "Sunset");
        put("צאת הכוכבים", "Nightfall");
        put("לא זמין", "Unavailable");
        put("תאריך", "Date");
        put("ימים", "Days");
        put("שעות", "Hours");
        put("שבועות", "Weeks");
        put("חודשים", "Months");
        put("שנים", "Years");
        put("כל", "Every");
        put("דקה", "Minute");
        put("שעה", "Hour");
        put("התחלה", "Start");
        put("סיום", "End");
        put("לפני / אחרי", "Before / After");
        put("שעות לפני", "Hours Before");
        put("מספר הבא", "Starting Number");
        put("קבועה", "Fixed");
        put("חד פעמית", "One Time");
        put("מחזורית", "Repeating");
        put("מחזוריות", "Repeating");
        put("תאריך עברי", "Hebrew date");
        put("אירוע שנתי", "Annual Event");
        put("זמני הלכה", "Halachic times");
        put("לפי זמני הלכה", "By halachic time");
        put("חיונית", "Critical");
        put("קובץ", "File");
        put("לטלפון", "To Phone");
        put("שליחה", "Send");
        put("העתקה", "Copy");
        put("מהתיקייה", "From Folder");
        put("בחר קובץ", "Choose File");
        put("שחזור מהלוח", "Restore from Clipboard");
        put("דחיית התזכורת", "Snooze Reminder");
        put("המופע הקרוב יידחה מהזמן שלו", "The next occurrence will be snoozed from its scheduled time");
        put("30 דקות", "30 min");
        put("15 דקות", "15 min");
        put("שעתיים", "2 hours");
        put("שעה", "1 hour");
        put("דחייה", "Snooze");
        put("דחה ביום", "Snooze 1 day");
        put("ההתראה נדחתה למחר לשעה", "Reminder snoozed until tomorrow at");
        put("בוצע", "Done");
        put("הבנתי", "Got it");
        put("תזכר אותי בעוד:", "Remind me in:");
        put("תזכר אותי לעוד שעה", "Remind me in 1 hour");
        put("שעה מקורית", "Original time");
        put("שעה אחרונה", "Latest time");
        put("ספרתי", "I Counted");
        put("דף", "Page");
        put("מתוך", "of");
        put("התראה מקדימה", "Advance reminder");
        put("שאלת ברכת", "Blessing question");
        put("הלילה יהיה אפשר להתחיל לברך ברכת הלבנה משעה", "Tonight Birkat Halevana can be recited starting at");
        put("האם ברכת ברכת הלבנה?", "Did you recite Birkat Halevana?");
        put("הלילה זה הלילה האחרון לברך ברכת הלבנה, ואפשר לברך כל הלילה.", "Tonight is the last night to recite Birkat Halevana, and it may be recited all night.");
        put("הלילה זה הלילה האחרון לברך ברכת הלבנה. סוף הזמן בשעה", "Tonight is the last night to recite Birkat Halevana. The final time is");
        put("אשר יצר", "Asher Yatzar");
        put("קריאת שמע בזמנה", "Shema on Time");
        put("בורא נפשות", "Borei Nefashot");
        put("מעין שלוש - על המחיה", "Me'ein Shalosh - Al Hamichya");
        put("מעין שלוש - על הגפן", "Me'ein Shalosh - Al Hagefen");
        put("מעין שלוש - על העץ", "Me'ein Shalosh - Al Ha'etz");
        put("ברכת המזון", "Birkat Hamazon");
        put("פתח תקווה, ישראל", "Petah Tikva, Israel");
        put("תזכורת חיונית לעוד", "Critical reminder in");
        put("זמן הברכה יוצג לפי עכשיו +", "The blessing time will be shown as now +");
        put("נוצרה תזכורת ל-", "Created reminder for ");
        put("לא ניתן לחשב את זמן ההלכה להיום", "Could not calculate today's halachic time");
        put("זמן התזכורת להיום כבר עבר", "Today's reminder time has already passed");
        put("כן", "Yes");
        put("לא", "No");
        put("סומן שבירכת ברכת הלבנה החודש", "Marked Birkat Halevana as recited for this month");
        put("הבא: מחשב...", "Next: calculating...");
        put("ההתראה הקרובה", "Next reminder");
        put("היום", "Today");
        put("מחר", "Tomorrow");
        put("אתמול", "Yesterday");
        put("יום לפני", "Previous Day");
        put("יום אחרי", "Next Day");
        put("עריכה", "Edit");
        put("מחיקה", "Delete");
        put("אין התראות שחלפו", "No past alerts");
        put("ביטול בוצע", "Undo Done");
        put("החזר כלא בוצע", "Mark Not Done");
        put("התזכורת כבר לא קיימת", "This reminder no longer exists");
        put("זמני שקט", "Quiet Times");
        put("בתקופות האלו רק תזכורות חיוניות יקפצו", "During these periods, only critical reminders will alert");
        put("אין עדיין זמני שקט", "No quiet times yet");
        put("מנחה וערבית", "Mincha and Maariv");
        put("זמן בפועל:", "Actual time:");
        put("חל עכשיו:", "Active now:");
        put("הקרוב:", "Next:");
        put("סומן מראש", "Marked in advance");
        put("זמן שקט חדש", "New Quiet Time");
        put("עריכת זמן שקט", "Edit Quiet Time");
        put("אפשר לבחור שעה רגילה או זמן הלכה", "Choose a regular time or a halachic time");
        put("לפי זמני הלכה", "By halachic time");
        put("התחלה", "Start");
        put("סיום", "End");
        put("תזכורות עד שעה", "Reminders until");
        put("בחירה לפי תאריך עברי", "Choose by Hebrew Date");
        put("יום", "Day");
        put("חודש", "Month");
        put("שנה", "Year");
        put("הצג", "Show");
        put("אין דפים שסומנו כלמדתי בימים האחרונים", "No pages were marked learned in the last few days");
        put("הדף הועבר להשלמה", "The page was moved to catch-up");
        put("התזכורת הקרובה:", "Next reminder:");
        put("מחוץ לימי הספירה", "Outside the Omer period");
        put("יום", "Day");
        put("להחיל שינויים מהטלפון?", "Apply changes from phone?");
        put("הטלפון שלח רק את השינויים שבוצעו שם. זה יעדכן/ימחק רק את מה שהשתנה ולא ידרוס דחיות, היסטוריה או מצב תפעולי אחר.", "The phone sent only the changes made there. This will update or delete only what changed and will not overwrite snoozes, history, or other runtime state.");
        put("החלה", "Apply");
        put("שחזור מהטלפון?", "Restore from phone?");
        put("הטלפון שלח גיבוי לשעון. לשחזר אותו עכשיו? כל התזכורות הקיימות יוחלפו.", "The phone sent a backup to the watch. Restore it now? All existing reminders will be replaced.");
        put("שחזור", "Restore");
        put("עבר הזמן", "Time has passed");
        put("אין מועד עתידי", "No future time");
        put("בחירה לפי תאריך לועזי", "Choose by Gregorian Date");
        put("שליחת לוגים", "Send Logs");
        put("ברכה", "Blessing");
        put("ממתין לענידת השעון", "Waiting for the watch to be worn");
        put("בודק תזכורות ברקע", "Checking reminders in the background");
        put("הגיבוי נשמר", "Backup saved");
        put("לא הצלחתי לשמור את הקובץ", "Could not save the file");
        put("בדיקה יומית ורשימת דפים להשלמה", "Daily check and catch-up pages");
        put("תזכורת בערבי הספירה לפי צאת הכוכבים", "Reminder on Omer nights based on nightfall");
        put("ייצוא גיבוי", "Export Backup");
        put("שמירה מחוץ לשעון", "Save outside the watch");
        put("שמירה יוצרת קובץ TXT בתיקיית Documents וגם ב-Download, כדי שיהיה קל למצוא אותו באפליקציית קבצים.", "Saving creates a TXT file in Documents and Download so it is easy to find in a file app.");
        put("הגיבוי הועתק", "Backup copied");
        put("ייבוא גיבוי", "Import Backup");
        put("בחירת קובץ לשחזור", "Choose a file to restore");
        put("השחזור יחליף את כל התזכורות הקיימות ויתזמן אותן מחדש", "Restoring replaces all existing reminders and schedules them again");
        put("אין גיבוי בלוח", "No backup in the clipboard");
        put("לא הצלחתי לשמור בתיקייה", "Could not save to the folder");
        put("שולח לטלפון...", "Sending to phone...");
        put("נשלח לטלפון", "Sent to phone");
        put("שולח לוגים לטלפון...", "Sending logs to phone...");
        put("הלוגים נשלחו לטלפון", "Logs sent to phone");
        put("הלוגים נמחקו", "Logs cleared");
        put("פותח את אפליקציית הגיבוי בטלפון...", "Opening the backup app on the phone...");
        put("פתחתי בטלפון. בחר גיבוי ושלח לשעון.", "Opened on the phone. Choose a backup and send it to the watch.");
        put("בורר הקבצים לא זמין בשעון", "The file picker is unavailable on the watch");
        put("לא נמצאו קבצי גיבוי בתיקייה", "No backup files were found in the folder");
        put("בחר גיבוי", "Choose Backup");
        put("אין טקסט גיבוי לייבוא", "No backup text to import");
        put("לשחזר גיבוי?", "Restore backup?");
        put("הגיבוי לא תקין", "The backup is invalid");
        put("הקובץ לא תקין", "The file is invalid");
        put("צריך לאשר מיקום ואז ללחוץ שוב", "Allow location and then tap again");
        put("לא ניתן לקבל מיקום", "Could not get location");
        put("המיקום עודכן", "Location updated");
        put("לא נמצא ספק מיקום פעיל", "No active location provider was found");
        put("מבקש מיקום חדש...", "Requesting a new location...");
        put("אין תזכורת קרובה לדחייה", "There is no upcoming reminder to snooze");
        put("לא הצלחתי ליצור גיבוי", "Could not create a backup");
        put("אין אפליקציה זמינה לשליחה", "No app is available for sending");
        put("לא נמצא טלפון מחובר", "No connected phone was found");
        put("לא הצלחתי לפתוח את האפליקציה בטלפון", "Could not open the app on the phone");
        put("לא הצלחתי למצוא טלפון מחובר", "Could not find a connected phone");
        put("השליחה לטלפון נכשלה", "Sending to the phone failed");
        put("שליחת הלוגים לטלפון נכשלה", "Sending logs to the phone failed");
        put("בדיקת תרופות", "Medication check");
        put("אין תזכורות קרובות", "No upcoming reminders");
        put("זמנים", "Times");
        put("היום", "Today");
        put("פתיחת זמני ההלכה של היום", "Open today's halachic times");
        put("פתיחת תזכורת לברכה", "Open blessing reminder");
        put("ייתכן שתזכורת לא הופיעה בזמן", "A reminder may not have appeared on time");
        put("ייתכן שתזכורות לא הופיעו בזמן", "Reminders may not have appeared on time");
        put("הפעל בדיקת רקע", "Enable Background Check");
        put("לא עכשיו", "Not Now");
        put("בדיקת רקע פעילה הופעלה. ניתן לשנות את מרווח הדקות בהגדרות המתקדמות.", "Background checking was enabled. You can change its interval in Advanced Settings.");
        put("אתה בטוח שאתה רוצה למחוק את הלוגים?", "Are you sure you want to clear the logs?");
        put("כל התזכורות הקיימות יוחלפו בתזכורות מהגיבוי.", "All existing reminders will be replaced with reminders from the backup.");
        put("ⓘ  אודות ורישיונות", "ⓘ  About & Licenses");
        put("אודות ורישיונות", "About & Licenses");
        put("רכיבי צד שלישי ב-Zmanio", "Third-party software in Zmanio");
        put("האפליקציה משתמשת בתוכנות קוד פתוח וברכיבי צד שלישי. תודה ליוצרים ולתורמים שלהם.", "This app uses open-source software and third-party components. We thank their authors and contributors.");
        put("הצג רישיון", "View License");
        put("נוסח הרישיון וההודעות", "License Text & Notices");
        put("חזרה לרישיונות", "Back to Licenses");
        put("לא ניתן לטעון את נוסח הרישיון", "The license text could not be loaded");
    }

    private UiText() {
    }

    public static String t(Context context, String value) {
        if (value == null) {
            return value;
        }
        Integer resId = RES.get(value);
        if (resId != null) {
            return context.getString(resId);
        }
        if (!AppLanguage.isEnglish(context)) {
            return value;
        }
        String exact = EN.get(value);
        return exact == null ? value : exact;
    }

    public static String[] translate(Context context, String[] values) {
        String[] translated = new String[values.length];
        for (int i = 0; i < values.length; i++) {
            translated[i] = t(context, values[i]);
        }
        return translated;
    }

    private static void put(String he, String en) {
        EN.put(he, en);
    }

    private static void res(String he, int stringRes) {
        RES.put(he, stringRes);
    }
}
