package com.woodpeckerbros.watchreminder;

import android.content.Context;

import java.util.HashMap;
import java.util.Map;

public class UiText {
    private static final Map<String, Integer> RES = new HashMap<>();

    static {
        res("לא בוצע", R.string.status_not_done);
        res("נדחה", R.string.status_snoozed);
        res("נדחה אוטומטית", R.string.status_auto_snoozed);
        res("תזכורת חדשה", R.string.ui_new_reminder);
        res("עריכת תזכורת", R.string.ui_edit_reminder);
        res("שם, זמן, סוג ופעילות", R.string.ui_reminder_editor_subtitle);
        res("הגדר", R.string.ui_configure);
        res("בדוק אם יש עדכון", R.string.ui_check_for_update);
        res("שם", R.string.ui_name);
        res("תיאור (אופציונלי)", R.string.ui_description_optional);
        res("תזכורת", R.string.ui_default_reminder_name);
        res("צריך לבחור זמן עתידי", R.string.ui_choose_future_time);
        res("מיקום", R.string.ui_location);
        res("פעילה", R.string.ui_enabled_feminine);
        res("חיונית", R.string.ui_critical);
        res("קבועה", R.string.ui_fixed);
        res("חד פעמית", R.string.ui_one_time);
        res("מחזורית", R.string.ui_repeating);
        res("מחזוריות", R.string.ui_repeating_title);
        res("אירוע שנתי", R.string.ui_annual_event);
        res("שנתית", R.string.ui_annual);
        res("שעה", R.string.ui_hour);
        res("דקה", R.string.ui_minute);
        res("דקות", R.string.ui_minutes);
        res("זמני הלכה", R.string.ui_halacha_times);
        res("לפני / אחרי", R.string.ui_before_after);
        res("שמירה", R.string.ui_save);
        res("ביטול", R.string.ui_cancel);
        res("כל", R.string.ui_every);
        res("שעות", R.string.ui_hours);
        res("ימים", R.string.ui_days);
        res("שבועות", R.string.ui_weeks);
        res("חודשים", R.string.ui_months);
        res("שנים", R.string.ui_years);
        res("תאריך עברי", R.string.ui_hebrew_date);
        res("התאריך הוא נקודת ההתחלה. בשנים/חודשים לפי תאריך עברי, האפליקציה ממירה בכל פעם לתאריך לועזי מתאים.", R.string.ui_periodic_hebrew_hint);
        res("שעות לפני", R.string.ui_hours_before);
        res("מספר הבא", R.string.ui_next_number);
        res("מספר התחלתי", R.string.ui_serial_number_hint);
        res("אם הוזן מספר התחלתי, הוא יוצג בסוגריים ויעלה ב-1 בכל שנה.", R.string.ui_annual_counter_hint);
        res("תאריך", R.string.ui_date);
        res("יום", R.string.ui_day);
        res("חודש", R.string.ui_month);
        res("שנה", R.string.ui_year);
        res("לא זמין", R.string.ui_unavailable);
        res("היום", R.string.ui_today);
        res("מחר", R.string.ui_tomorrow);
        res("אתמול", R.string.ui_yesterday);
        res("אין התראות שחלפו", R.string.ui_no_past_alerts);
        res("ביטול בוצע", R.string.ui_done_undo);
        res("החלה", R.string.ui_apply);
        res("שחזור", R.string.ui_restore);
        res("עריכה", R.string.ui_edit);
        res("מחיקה", R.string.ui_delete);
        res("יום לפני", R.string.ui_previous_day);
        res("יום אחרי", R.string.ui_next_day);

        res("הוספה", R.string.ui_legacy_001);
        res("+ תזכורת", R.string.ui_legacy_002);
        res("היסטוריה", R.string.ui_legacy_003);
        res("תזכורות", R.string.ui_legacy_004);
        res("כל התזכורות", R.string.ui_legacy_005);
        res("לחיצה לעריכה · לחיצה ארוכה לפעולות", R.string.ui_legacy_006);
        res("חזרה לבית", R.string.ui_legacy_007);
        res("מה חשוב עכשיו", R.string.ui_legacy_008);
        res("התזכורת הבאה", R.string.ui_legacy_009);
        res("אחר כך", R.string.ui_legacy_010);
        res("גישה מהירה", R.string.ui_legacy_011);
        res("אין תזכורות קרובות", R.string.ui_legacy_012);
        res("אפשר להוסיף תזכורת חדשה בלחיצה אחת", R.string.ui_legacy_013);
        res("בוקר טוב", R.string.ui_legacy_014);
        res("צהריים טובים", R.string.ui_legacy_015);
        res("ערב טוב", R.string.ui_legacy_016);
        res("לחיצה ארוכה על תזכורת פותחת פעולות אפשריות", R.string.ui_legacy_017);
        res("אין תזכורות", R.string.ui_legacy_018);
        res("טוען תזכורות...", R.string.ui_legacy_019);
        res("טוען עוד תזכורות...", R.string.ui_legacy_020);
        res("צריך לאשר Alarms & reminders כדי לקבל תזכורות בזמן", R.string.ui_legacy_021);
        res("לחץ כאן כדי לאשר Alarms & reminders לתזכורות מדויקות", R.string.ui_legacy_022);
        res("צריך לאשר התראות במסך מלא כדי שהתזכורת תיפתח על המסך", R.string.ui_legacy_023);
        res("דחה", R.string.ui_legacy_024);
        res("זמני היום בהלכה", R.string.ui_legacy_025);
        res("זמני היום", R.string.ui_legacy_026);
        res("תזכורת לברכה", R.string.ui_legacy_027);
        res("תזכורת", R.string.ui_legacy_028);
        res("הגדרות", R.string.ui_legacy_029);
        res("חזרה", R.string.ui_legacy_030);
        res("שמירה", R.string.ui_legacy_031);
        res("ביטול", R.string.ui_legacy_032);
        res("ניקוי הכל", R.string.ui_legacy_033);
        res("מנקה היסטוריה...", R.string.ui_legacy_034);
        res("ההיסטוריה נמחקה", R.string.ui_legacy_035);
        res("לא הצלחתי לנקות את ההיסטוריה", R.string.ui_legacy_036);
        res("ניקוי לוגים", R.string.ui_legacy_037);
        res("לוגים", R.string.ui_legacy_038);
        res("לוגים לטלפון", R.string.ui_legacy_039);
        res("לבדיקת תזכורות שלא קופצות בזמן", R.string.ui_legacy_040);
        res("גיבוי ושחזור", R.string.ui_legacy_041);
        res("גיבוי לטלפון", R.string.ui_legacy_042);
        res("שחזור מהטלפון", R.string.ui_legacy_043);
        res("התראה", R.string.ui_legacy_044);
        res("תזכורות רגילות", R.string.ui_legacy_045);
        res("ניטור תזכורות", R.string.ui_legacy_046);
        res("המתנה לענידת השעון", R.string.ui_legacy_047);
        res("רטט", R.string.ui_legacy_048);
        res("צלצול", R.string.ui_legacy_049);
        res("בחירת צלצול", R.string.ui_legacy_050);
        res("לחיצה משמיעה דוגמה", R.string.ui_legacy_051);
        res("ברירת מחדל", R.string.ui_legacy_052);
        res("קלאסי", R.string.ui_legacy_053);
        res("מנגינות", R.string.ui_legacy_054);
        res("טבע ורגוע", R.string.ui_legacy_055);
        res("עוצמת רטט", R.string.ui_legacy_056);
        res("צלצול ברירת מחדל", R.string.ui_legacy_057);
        res("עוצמת צלצול", R.string.ui_legacy_058);
        res("אורך התראה בשניות", R.string.ui_legacy_059);
        res("לא הצלחתי לפתוח בחירת צלצול", R.string.ui_legacy_060);
        res("רגיל", R.string.ui_legacy_061);
        res("עדין", R.string.ui_legacy_062);
        res("חזק", R.string.ui_legacy_063);
        res("ארוך", R.string.ui_legacy_064);
        res("ללא רטט", R.string.ui_legacy_065);
        res("אורך רטט בשניות", R.string.ui_legacy_066);
        res("ניטור תזכורות פעיל", R.string.ui_legacy_067);
        res("ברירת מחדל: כל 3 דקות", R.string.ui_legacy_068);
        res("דקות", R.string.ui_legacy_069);
        res("שניות", R.string.ui_legacy_070);
        res("דחייה אוטומטית", R.string.ui_legacy_071);
        res("אם אין תגובה, המסך נסגר והתזכורת נדחית", R.string.ui_legacy_072);
        res("המתנה לתגובה לפני סגירה (שניות)", R.string.ui_legacy_073);
        res("הקפצה חוזרת לאחר סגירה (דקות)", R.string.ui_legacy_074);
        res("כמה דקות אחרי החיוב להזכיר לברך", R.string.ui_legacy_075);
        res("זמני שקט - לא להפריע", R.string.ui_legacy_076);
        res("ברכת הלבנה", R.string.ui_legacy_077);
        res("סמן שבירכתי", R.string.ui_legacy_078);
        res("דף היומי", R.string.ui_legacy_079);
        res("ספירת העומר", R.string.ui_legacy_080);
        res("צום לסירוגין", R.string.ui_legacy_081);
        res("מצב נוכחי", R.string.ui_legacy_082);
        res("שעות צום וחלון אכילה", R.string.ui_legacy_083);
        res("חלון האכילה מחושב אוטומטית מתוך 24 שעות", R.string.ui_legacy_084);
        res("שעות צום", R.string.ui_legacy_085);
        res("התחלת אכילה ראשונית", R.string.ui_legacy_086);
        res("לדוגמה 12:00 עם 19 שעות צום יוצר חלון 12:00-17:00", R.string.ui_legacy_087);
        res("סיימתי לאכול", R.string.ui_legacy_088);
        res("התחלתי לאכול", R.string.ui_legacy_089);
        res("חלון האכילה התחיל עכשיו", R.string.ui_legacy_090);
        res("סומן שהתחלת לאכול ב-", R.string.ui_legacy_091);
        res("אפשר לבחור זמן סיום רק אחרי פתיחת חלון האכילה", R.string.ui_legacy_092);
        res("סומן שסיימת לאכול. חלון האכילה הבא יתעדכן לפי זמן הסיום.", R.string.ui_legacy_093);
        res("בחירת זמן ידנית", R.string.ui_legacy_094);
        res("זמן סיום", R.string.ui_legacy_095);
        res("זמן התחלה", R.string.ui_legacy_096);
        res("התחלתי לאכול בשעה", R.string.ui_legacy_097);
        res("סיימתי לאכול בשעה", R.string.ui_legacy_098);
        res("בחר זמן התחלה", R.string.ui_legacy_099);
        res("בחר זמן סיום", R.string.ui_legacy_100);
        res("אי אפשר לבחור זמן סיום עתידי", R.string.ui_legacy_101);
        res("סומן שסיימת לאכול ב-", R.string.ui_legacy_102);
        res("אפשר להתחיל לאכול", R.string.ui_legacy_103);
        res("עוד חצי שעה לסיום", R.string.ui_legacy_104);
        res("חלון האכילה ייסגר בעוד חצי שעה.", R.string.ui_legacy_105);
        res("חלון האכילה נסגר", R.string.ui_legacy_106);
        res("נגמר חלון זמן האכילה להיום.", R.string.ui_legacy_107);
        res("יש לך תזכורת לצום לסירוגין.", R.string.ui_legacy_108);
        res("תחזור עד שתלחץ הבנתי.", R.string.ui_legacy_109);
        res("הצום נגמר ב:", R.string.ui_legacy_110);
        res("הצום מתחיל ב:", R.string.ui_legacy_111);
        res("מיקום זמני הלכה", R.string.ui_legacy_112);
        res("מיקום חדש", R.string.ui_legacy_113);
        res("זהה שם עיר", R.string.ui_legacy_114);
        res("מזהה שם עיר...", R.string.ui_legacy_115);
        res("שם העיר עודכן", R.string.ui_legacy_116);
        res("אין תשובה מהשרת; הוצג יישוב קרוב", R.string.ui_legacy_117);
        res("אין תשובה מהשרת; נשמרו הקואורדינטות", R.string.ui_legacy_118);
        res("המיקום עודכן", R.string.ui_legacy_119);
        res("לשליחה כשיש תקלה בתזכורות", R.string.ui_legacy_120);
        res("גיבוי ושחזור מתבצעים דרך אפליקציית הטלפון", R.string.ui_legacy_121);
        res("פעיל", R.string.ui_legacy_122);
        res("פעילה", R.string.ui_legacy_123);
        res("כבוי", R.string.ui_legacy_124);
        res("תזכורת דף היומי פעילה", R.string.ui_legacy_125);
        res("זמן לתזכורת", R.string.ui_legacy_126);
        res("אפשר לדחות", R.string.ui_legacy_127);
        res("בדיקת לימוד דף היומי", R.string.ui_legacy_128);
        res("תיקון סימון", R.string.ui_legacy_129);
        res("אם סימנת בטעות שלמדת, אפשר להחזיר דף לרשימת ההשלמות", R.string.ui_legacy_130);
        res("אין דפים שסומנו כלמדתי בימים האחרונים", R.string.ui_legacy_131);
        res("סמן כלא למדתי", R.string.ui_legacy_132);
        res("דפים להשלמה", R.string.ui_legacy_133);
        res("אין דפים שמסומנים כלא למדתי", R.string.ui_legacy_134);
        res("סמן הכל כהושלם", R.string.ui_legacy_135);
        res("סימון כל הדפים כהושלמו", R.string.ui_legacy_136);
        res("האם לסמן את כל הדפים שברשימת ההשלמה כנלמדו? פעולה זו תסיר את כולם מהרשימה.", R.string.ui_legacy_137);
        res("המשך", R.string.ui_legacy_138);
        res("למדתי את הדף", R.string.ui_legacy_139);
        res("תזכורת ספירת העומר פעילה", R.string.ui_legacy_140);
        res("תזכורת לספירת העומר", R.string.ui_legacy_141);
        res("כמה דקות אחרי צאת הכוכבים להזכיר", R.string.ui_legacy_142);
        res("דקות אחרי צאת הכוכבים", R.string.ui_legacy_143);
        res("מחוץ לימי הספירה כרגע", R.string.ui_legacy_144);
        res("התזכורת הקרובה:", R.string.ui_legacy_145);
        res("בחירת תאריך", R.string.ui_legacy_146);
        res("הצג", R.string.ui_legacy_147);
        res("בחירה לפי תאריך לועזי", R.string.ui_legacy_148);
        res("בחירה לפי תאריך עברי", R.string.ui_legacy_149);
        res("שפה", R.string.ui_legacy_150);
        res("שפת הממשק", R.string.ui_legacy_151);
        res("אוטומטי לפי השעון", R.string.ui_legacy_152);
        res("עברית", R.string.ui_legacy_153);
        res("אנגלית", R.string.ui_legacy_154);
        res("שעון מעורר חכם", R.string.ui_legacy_155);
        res("רקע מסך ההתראה", R.string.ui_legacy_156);
        res("זריחה חזקה", R.string.ui_legacy_157);
        res("בוקר מוקדם", R.string.ui_legacy_158);
        res("משתנה לפי השעה", R.string.ui_legacy_159);
        res("בוקר", R.string.ui_legacy_160); res("צהריים", R.string.ui_legacy_161);
        res("ערב", R.string.ui_legacy_162); res("לילה", R.string.ui_legacy_163);
        res("אופן כיבוי השעון", R.string.ui_legacy_164);
        res("לחיצה רגילה", R.string.ui_legacy_165);
        res("לחיצה ארוכה", R.string.ui_legacy_166);
        res("לחיצה כפולה", R.string.ui_legacy_167);
        res("משך לחיצה ארוכה בשניות", R.string.ui_legacy_168);
        res("ניעור היד", R.string.ui_legacy_169); res("הליכה", R.string.ui_legacy_170);
        res("תרגיל חשבון", R.string.ui_legacy_171); res("תרגיל זיכרון", R.string.ui_legacy_172);
        res("לחיצות מתחלפות", R.string.ui_legacy_173); res("משימה אקראית", R.string.ui_legacy_174);
        res("שילוב שתי משימות", R.string.ui_legacy_175);
        res("משימות מרובות", R.string.ui_legacy_176);
        res("בחרו את משימות ההשכמה", R.string.ui_legacy_177);
        res("יש לבחור לפחות שתי משימות", R.string.ui_legacy_178);
        res("מספר ניעורים", R.string.ui_legacy_179); res("מספר צעדים", R.string.ui_legacy_180);
        res("מספר לחיצות מתחלפות", R.string.ui_legacy_181);
        res("רמת חשבון", R.string.ui_legacy_182); res("רמת זיכרון", R.string.ui_legacy_183);
        res("הצגת דוגמת חשבון", R.string.ui_legacy_184); res("הצגת דוגמת זיכרון", R.string.ui_legacy_185);
        res("בדיקת ערנות", R.string.ui_legacy_186);
        res("בדיקת ערנות לאחר הכיבוי", R.string.ui_legacy_187);
        res("בדיקת ערנות אחרי דקות", R.string.ui_legacy_188);
        res("גיבוי רטט של השעון", R.string.ui_legacy_189);
        res("הפעלת גיבוי שעון מערכת", R.string.ui_legacy_190);
        res("אם לא תתעוררו עד סוף ההתראה, האפליקציה תנסה להפעיל טיימר חד־פעמי בשעון המערכת. הצליל והרטט יפעלו לפי הגדרות השעון, ולא לפי הגדרות האפליקציה.", R.string.ui_legacy_191);
        res("גרסה", R.string.ui_legacy_192);
        res("לא ידועה", R.string.ui_legacy_193);
        res("דוגמת תרגיל חשבון", R.string.ui_legacy_194); res("דוגמת תרגיל זיכרון", R.string.ui_legacy_195);
        res("נכון — כך תתקדמו לשאלה הבאה", R.string.ui_legacy_196);
        res("לא נכון — נסו שוב", R.string.ui_legacy_197);
        res("עכשיו יש לחזור על הרצף בעזרת ארבעת כפתורי הצבע", R.string.ui_legacy_198);
        res("נסו את השעון", R.string.ui_legacy_199);
        res("שעונים מעוררים חכמים", R.string.ui_legacy_200);
        res("עדיין לא הוגדר שעון מעורר חכם", R.string.ui_legacy_201);
        res("הוספת שעון מעורר", R.string.ui_legacy_202);
        res("מחיקת שעון מעורר", R.string.ui_legacy_203);
        res("שעון מעורר פעיל", R.string.ui_legacy_204);
        res("שעת השכמה", R.string.ui_legacy_205);
        res("ימי פעילות", R.string.ui_legacy_206);
        res("חלון השכמה חכם", R.string.ui_legacy_207);
        res("דקות לפני שעת ההשכמה", R.string.ui_legacy_208);
        res("נודניק", R.string.ui_legacy_209);
        res("כל כמה דקות", R.string.ui_legacy_210);
        res("מספר פעמים", R.string.ui_legacy_211);
        res("0 פעמים מבטל את אפשרות הנודניק", R.string.ui_legacy_212);
        res("רטט וצלצול", R.string.ui_legacy_213);
        res("עוצמה עדינה", R.string.ui_legacy_214);
        res("עוצמה בינונית", R.string.ui_legacy_215);
        res("עוצמה חזקה", R.string.ui_legacy_216);
        res("משך ההתראה בשניות", R.string.ui_legacy_217);
        res("צריך לבחור לפחות יום אחד", R.string.ui_legacy_218);
        res("השעון המעורר נשמר", R.string.ui_legacy_219);
        res("זמנים יהודיים", R.string.ui_legacy_220);
        res("קריאת שמע של ערבית בזמנה", R.string.ui_legacy_221);
        res("כמה דקות אחרי צאת הכוכבים לתזכר. אם הזמן כבר עבר, התזכורת תוגדר לפי ההגדרה הכללית למעלה.", R.string.ui_legacy_222);
        res("רטט וצלילים", R.string.ui_legacy_223);
        res("הגדרות מתקדמות", R.string.ui_legacy_224);
        res("מצב יהודי כבוי", R.string.ui_legacy_225);
        res("מצב יהודי", R.string.ui_legacy_226);
        res("מציג תאריך עברי, זמני הלכה, ברכות, דף יומי וספירת העומר", R.string.ui_legacy_227);
        res("אם ההתראות לא מתקבלות בזמן, אפשר להפעיל ניטור תזכורות פעיל. בדיקת תקינות קלה מתבצעת בערך פעם בשעה.", R.string.ui_legacy_228);
        res("לתזכר ימים יהודיים", R.string.ui_legacy_229);
        res("ימים יהודיים", R.string.ui_legacy_230);
        res("תזכורת תקופה", R.string.ui_legacy_231);
        res("לתזכר זמן תקופה", R.string.ui_legacy_232);
        res("זמן התקופה", R.string.ui_legacy_233);
        res("תקופת ניסן", R.string.ui_legacy_234);
        res("תקופת תמוז", R.string.ui_legacy_235);
        res("תקופת תשרי", R.string.ui_legacy_236);
        res("תקופת טבת", R.string.ui_legacy_237);
        res("תזכורת מקדימה לזמן התקופה", R.string.ui_legacy_238);
        res("זמן התקופה מתחיל עכשיו", R.string.ui_legacy_239);
        res("חלון", R.string.ui_legacy_240);
        res("יש להימנע משתיית מים גלויים מ־", R.string.ui_legacy_241);
        res("עד", R.string.ui_legacy_242);
        res("לא נמצאה תקופה קרובה", R.string.ui_legacy_243);
        res("יום כיפור קטן", R.string.ui_legacy_244);
        res("פרשת השבוע", R.string.ui_legacy_245);
        res("שבת מיוחדת", R.string.ui_legacy_246);
        res("זמני שבת", R.string.ui_legacy_247);
        res("הדלקת נרות", R.string.ui_legacy_248);
        res("צאת שבת", R.string.ui_legacy_249);
        res("צאת שבת ר״ת", R.string.ui_legacy_250);
        res("עלות השחר", R.string.ui_legacy_251);
        res("זריחה", R.string.ui_legacy_252);
        res("סוף זמן שמע מג״א", R.string.ui_legacy_253);
        res("סוף זמן שמע גר״א", R.string.ui_legacy_254);
        res("סוף זמן ברכות ק״ש", R.string.ui_legacy_255);
        res("חצות", R.string.ui_legacy_256);
        res("חצות יום", R.string.ui_legacy_257);
        res("חצות לילה", R.string.ui_legacy_258);
        res("צ.כוכבים ר״ת", R.string.ui_legacy_259);
        res("דף היומי בבלי", R.string.ui_legacy_260);
        res("דף היומי ירושלמי", R.string.ui_legacy_261);
        res("מנחה גדולה", R.string.ui_legacy_262);
        res("מנחה קטנה", R.string.ui_legacy_263);
        res("פלג המנחה", R.string.ui_legacy_264);
        res("שקיעה", R.string.ui_legacy_265);
        res("צאת הכוכבים", R.string.ui_legacy_266);
        res("לא זמין", R.string.ui_legacy_267);
        res("תאריך", R.string.ui_legacy_268);
        res("ימים", R.string.ui_legacy_269);
        res("שעות", R.string.ui_legacy_270);
        res("שבועות", R.string.ui_legacy_271);
        res("חודשים", R.string.ui_legacy_272);
        res("שנים", R.string.ui_legacy_273);
        res("כל", R.string.ui_legacy_274);
        res("דקה", R.string.ui_legacy_275);
        res("שעה", R.string.ui_legacy_276);
        res("התחלה", R.string.ui_legacy_277);
        res("סיום", R.string.ui_legacy_278);
        res("לפני / אחרי", R.string.ui_legacy_279);
        res("שעות לפני", R.string.ui_legacy_280);
        res("מספר הבא", R.string.ui_legacy_281);
        res("קבועה", R.string.ui_legacy_282);
        res("חד פעמית", R.string.ui_legacy_283);
        res("מחזורית", R.string.ui_legacy_284);
        res("מחזוריות", R.string.ui_legacy_285);
        res("תאריך עברי", R.string.ui_legacy_286);
        res("אירוע שנתי", R.string.ui_legacy_287);
        res("זמני הלכה", R.string.ui_legacy_288);
        res("לפי זמני הלכה", R.string.ui_legacy_289);
        res("חיונית", R.string.ui_legacy_290);
        res("קובץ", R.string.ui_legacy_291);
        res("לטלפון", R.string.ui_legacy_292);
        res("שליחה", R.string.ui_legacy_293);
        res("העתקה", R.string.ui_legacy_294);
        res("מהתיקייה", R.string.ui_legacy_295);
        res("בחר קובץ", R.string.ui_legacy_296);
        res("שחזור מהלוח", R.string.ui_legacy_297);
        res("דחיית התזכורת", R.string.ui_legacy_298);
        res("המופע הקרוב יידחה מהזמן שלו", R.string.ui_legacy_299);
        res("30 דקות", R.string.ui_legacy_300);
        res("15 דקות", R.string.ui_legacy_301);
        res("שעתיים", R.string.ui_legacy_302);
        res("שעה", R.string.ui_legacy_276);
        res("דחייה", R.string.ui_legacy_303);
        res("דחה ביום", R.string.ui_legacy_304);
        res("ההתראה נדחתה למחר לשעה", R.string.ui_legacy_305);
        res("בוצע", R.string.ui_legacy_306);
        res("הבנתי", R.string.ui_legacy_307);
        res("תזכר אותי בעוד:", R.string.ui_legacy_308);
        res("תזכר אותי לעוד שעה", R.string.ui_legacy_309);
        res("שעה מקורית", R.string.ui_legacy_310);
        res("שעה אחרונה", R.string.ui_legacy_311);
        res("ספרתי", R.string.ui_legacy_312);
        res("דף", R.string.ui_legacy_313);
        res("מתוך", R.string.ui_legacy_314);
        res("התראה מקדימה", R.string.ui_legacy_315);
        res("שאלת ברכת", R.string.ui_legacy_316);
        res("הלילה יהיה אפשר להתחיל לברך ברכת הלבנה משעה", R.string.ui_legacy_317);
        res("האם ברכת ברכת הלבנה?", R.string.ui_legacy_318);
        res("הלילה זה הלילה האחרון לברך ברכת הלבנה, ואפשר לברך כל הלילה.", R.string.ui_legacy_319);
        res("הלילה זה הלילה האחרון לברך ברכת הלבנה. סוף הזמן בשעה", R.string.ui_legacy_320);
        res("אשר יצר", R.string.ui_legacy_321);
        res("קריאת שמע בזמנה", R.string.ui_legacy_322);
        res("בורא נפשות", R.string.ui_legacy_323);
        res("מעין שלוש - על המחיה", R.string.ui_legacy_324);
        res("מעין שלוש - על הגפן", R.string.ui_legacy_325);
        res("מעין שלוש - על העץ", R.string.ui_legacy_326);
        res("ברכת המזון", R.string.ui_legacy_327);
        res("פתח תקווה, ישראל", R.string.ui_legacy_328);
        res("תזכורת חיונית לעוד", R.string.ui_legacy_329);
        res("זמן הברכה יוצג לפי עכשיו +", R.string.ui_legacy_330);
        res("נוצרה תזכורת ל-", R.string.ui_legacy_331);
        res("לא ניתן לחשב את זמן ההלכה להיום", R.string.ui_legacy_332);
        res("זמן התזכורת להיום כבר עבר", R.string.ui_legacy_333);
        res("כן", R.string.ui_legacy_334);
        res("לא", R.string.ui_legacy_335);
        res("סומן שבירכת ברכת הלבנה החודש", R.string.ui_legacy_336);
        res("הבא: מחשב...", R.string.ui_legacy_337);
        res("ההתראה הקרובה", R.string.ui_legacy_338);
        res("היום", R.string.ui_legacy_339);
        res("מחר", R.string.ui_legacy_340);
        res("אתמול", R.string.ui_legacy_341);
        res("יום לפני", R.string.ui_legacy_342);
        res("יום אחרי", R.string.ui_legacy_343);
        res("עריכה", R.string.ui_legacy_344);
        res("מחיקה", R.string.ui_legacy_345);
        res("אין התראות שחלפו", R.string.ui_legacy_346);
        res("ביטול בוצע", R.string.ui_legacy_347);
        res("החזר כלא בוצע", R.string.ui_legacy_348);
        res("התזכורת כבר לא קיימת", R.string.ui_legacy_349);
        res("זמני שקט", R.string.ui_legacy_350);
        res("בתקופות האלו רק תזכורות חיוניות יקפצו", R.string.ui_legacy_351);
        res("אין עדיין זמני שקט", R.string.ui_legacy_352);
        res("מנחה וערבית", R.string.ui_legacy_353);
        res("זמן בפועל:", R.string.ui_legacy_354);
        res("חל עכשיו:", R.string.ui_legacy_355);
        res("הקרוב:", R.string.ui_legacy_356);
        res("סומן מראש", R.string.ui_legacy_357);
        res("זמן שקט חדש", R.string.ui_legacy_358);
        res("עריכת זמן שקט", R.string.ui_legacy_359);
        res("אפשר לבחור שעה רגילה או זמן הלכה", R.string.ui_legacy_360);
        res("לפי זמני הלכה", R.string.ui_legacy_289);
        res("התחלה", R.string.ui_legacy_277);
        res("סיום", R.string.ui_legacy_278);
        res("תזכורות עד שעה", R.string.ui_legacy_361);
        res("בחירה לפי תאריך עברי", R.string.ui_legacy_149);
        res("יום", R.string.ui_legacy_362);
        res("חודש", R.string.ui_legacy_363);
        res("שנה", R.string.ui_legacy_364);
        res("הצג", R.string.ui_legacy_147);
        res("אין דפים שסומנו כלמדתי בימים האחרונים", R.string.ui_legacy_131);
        res("הדף הועבר להשלמה", R.string.ui_legacy_365);
        res("התזכורת הקרובה:", R.string.ui_legacy_145);
        res("מחוץ לימי הספירה", R.string.ui_legacy_366);
        res("יום", R.string.ui_legacy_362);
        res("להחיל שינויים מהטלפון?", R.string.ui_legacy_367);
        res("הטלפון שלח רק את השינויים שבוצעו שם. זה יעדכן/ימחק רק את מה שהשתנה ולא ידרוס דחיות, היסטוריה או מצב תפעולי אחר.", R.string.ui_legacy_368);
        res("החלה", R.string.ui_legacy_369);
        res("שחזור מהטלפון?", R.string.ui_legacy_370);
        res("הטלפון שלח גיבוי לשעון. לשחזר אותו עכשיו? כל התזכורות הקיימות יוחלפו.", R.string.ui_legacy_371);
        res("שחזור", R.string.ui_legacy_372);
        res("עבר הזמן", R.string.ui_legacy_373);
        res("אין מועד עתידי", R.string.ui_legacy_374);
        res("בחירה לפי תאריך לועזי", R.string.ui_legacy_148);
        res("שליחת לוגים", R.string.ui_legacy_375);
        res("ברכה", R.string.ui_legacy_376);
        res("ממתין לענידת השעון", R.string.ui_legacy_377);
        res("בודק תזכורות ברקע", R.string.ui_legacy_378);
        res("הגיבוי נשמר", R.string.ui_legacy_379);
        res("לא הצלחתי לשמור את הקובץ", R.string.ui_legacy_380);
        res("בדיקה יומית ורשימת דפים להשלמה", R.string.ui_legacy_381);
        res("תזכורת בערבי הספירה לפי צאת הכוכבים", R.string.ui_legacy_382);
        res("ייצוא גיבוי", R.string.ui_legacy_383);
        res("שמירה מחוץ לשעון", R.string.ui_legacy_384);
        res("שמירה יוצרת קובץ TXT בתיקיית Documents וגם ב-Download, כדי שיהיה קל למצוא אותו באפליקציית קבצים.", R.string.ui_legacy_385);
        res("הגיבוי הועתק", R.string.ui_legacy_386);
        res("ייבוא גיבוי", R.string.ui_legacy_387);
        res("בחירת קובץ לשחזור", R.string.ui_legacy_388);
        res("השחזור יחליף את כל התזכורות הקיימות ויתזמן אותן מחדש", R.string.ui_legacy_389);
        res("אין גיבוי בלוח", R.string.ui_legacy_390);
        res("לא הצלחתי לשמור בתיקייה", R.string.ui_legacy_391);
        res("שולח לטלפון...", R.string.ui_legacy_392);
        res("נשלח לטלפון", R.string.ui_legacy_393);
        res("שולח לוגים לטלפון...", R.string.ui_legacy_394);
        res("הלוגים נשלחו לטלפון", R.string.ui_legacy_395);
        res("הלוגים נמחקו", R.string.ui_legacy_396);
        res("פותח את אפליקציית הגיבוי בטלפון...", R.string.ui_legacy_397);
        res("פתחתי בטלפון. בחר גיבוי ושלח לשעון.", R.string.ui_legacy_398);
        res("בורר הקבצים לא זמין בשעון", R.string.ui_legacy_399);
        res("לא נמצאו קבצי גיבוי בתיקייה", R.string.ui_legacy_400);
        res("בחר גיבוי", R.string.ui_legacy_401);
        res("אין טקסט גיבוי לייבוא", R.string.ui_legacy_402);
        res("לשחזר גיבוי?", R.string.ui_legacy_403);
        res("הגיבוי לא תקין", R.string.ui_legacy_404);
        res("הקובץ לא תקין", R.string.ui_legacy_405);
        res("צריך לאשר מיקום ואז ללחוץ שוב", R.string.ui_legacy_406);
        res("לא ניתן לקבל מיקום", R.string.ui_legacy_407);
        res("המיקום עודכן", R.string.ui_legacy_119);
        res("לא נמצא ספק מיקום פעיל", R.string.ui_legacy_408);
        res("מבקש מיקום חדש...", R.string.ui_legacy_409);
        res("אין תזכורת קרובה לדחייה", R.string.ui_legacy_410);
        res("לא הצלחתי ליצור גיבוי", R.string.ui_legacy_411);
        res("אין אפליקציה זמינה לשליחה", R.string.ui_legacy_412);
        res("לא נמצא טלפון מחובר", R.string.ui_legacy_413);
        res("לא הצלחתי לפתוח את האפליקציה בטלפון", R.string.ui_legacy_414);
        res("לא הצלחתי למצוא טלפון מחובר", R.string.ui_legacy_415);
        res("השליחה לטלפון נכשלה", R.string.ui_legacy_416);
        res("שליחת הלוגים לטלפון נכשלה", R.string.ui_legacy_417);
        res("בדיקת תרופות", R.string.ui_legacy_418);
        res("אין תזכורות קרובות", R.string.ui_legacy_012);
        res("זמנים", R.string.ui_legacy_419);
        res("היום", R.string.ui_legacy_339);
        res("פתיחת זמני ההלכה של היום", R.string.ui_legacy_420);
        res("פתיחת תזכורת לברכה", R.string.ui_legacy_421);
        res("ייתכן שתזכורת לא הופיעה בזמן", R.string.ui_legacy_422);
        res("ייתכן שתזכורות לא הופיעו בזמן", R.string.ui_legacy_423);
        res("הפעל ניטור תזכורות", R.string.ui_legacy_424);
        res("לא עכשיו", R.string.ui_legacy_425);
        res("ניטור התזכורות הופעל. בדיקת התקינות מתבצעת בערך פעם בשעה.", R.string.ui_legacy_426);
        res("אתה בטוח שאתה רוצה למחוק את הלוגים?", R.string.ui_legacy_427);
        res("כל התזכורות הקיימות יוחלפו בתזכורות מהגיבוי.", R.string.ui_legacy_428);
        res("ⓘ  אודות ורישיונות", R.string.ui_legacy_429);
        res("אודות ורישיונות", R.string.ui_legacy_430);
        res("רכיבי צד שלישי ב-Zmanio", R.string.ui_legacy_431);
        res("האפליקציה משתמשת בתוכנות קוד פתוח וברכיבי צד שלישי. תודה ליוצרים ולתורמים שלהם.", R.string.ui_legacy_432);
        res("הצג רישיון", R.string.ui_legacy_433);
        res("נוסח הרישיון וההודעות", R.string.ui_legacy_434);
        res("חזרה לרישיונות", R.string.ui_legacy_435);
        res("לא ניתן לטעון את נוסח הרישיון", R.string.ui_legacy_436);
    }

    private UiText() {
    }

    public static String t(Context context, String value) {
        if (value == null) {
            return value;
        }
        Integer resId = RES.get(value);
        if (resId != null) {
            return context.getString(resId);
        }
        return value;
    }

    public static String[] translate(Context context, String[] values) {
        String[] translated = new String[values.length];
        for (int i = 0; i < values.length; i++) {
            translated[i] = t(context, values[i]);
        }
        return translated;
    }

    private static void res(String he, int stringRes) {
        RES.put(he, stringRes);
    }
}
